-- create IT_COMPANY DATABASE;
-- use IT_COMPNAY;
use sample;

-- return current time, date and timestamp
SELECT CURTIME(), CURDATE(),NOW();
SELECT CURRENT_TIME(), CURRENT_DATE(),CURRENT_TIMESTAMP();

-- RETURN YEAR, MONTH, DAY FROM CURRENT DATE
SELECT YEAR(CURDATE()), MONTH(CURDATE()),DAY(CURDATE());
-- RETURN HOURS, MINUTES, SECONDS FROM CURRENT TIME STAMP
-- RETURN CURRENT QUARTER AND WEEK
-- FROM SAMPLE TABLE HIREDATE FORMAT CHANGE TO 10/12/2025
-- DESC IT_COMPANY;
SELECT HIRE_DATE, STR_TO_DATE(HIRE_DATE, '%d-%b-%y') FROM IT_COMPANY;
SELECT HIRE_DATE;
SELECT HIRE_DATE, DATE_FORMAT(HIRE_DATE, '%d/%m/%Y') FROM EMPLOYEE;
-- FIND TOTAL EMPLOYEES COUNT RELATED